### ISSUE TITLE
Light intensity Android

### ISSUE THREAD

**Issue by besessener** [woodenshark/prismatik-for-android#1]
Hello,
is there a way to increase light intensity for prismatik running on Ouya? When I used lightpack with my Raspberry Pi and Hyperion I was able to change it, and was pretty bright then. Id like to have same results with Ouya though. Now it's always so dark, I can barely see the light at the wall, unless the WHOLE screen is in a neon color already. Suggestions? :)

**Comment by zzpin** [comment]
Hello,
I encounter the same problem with the ouya on the option "screen capturing" mode.
"solid color" and "mood lamp" are looking good but thats not the mean option tu use this on the ouya
How can i adjust the brightness of lightpack in screen capturing mode on the ouya (android)

Many thanks for your assistants

**Comment by e-yes** [comment]
Related issue: https://github.com/woodenshark/prismatik-for-android/issues/6

**Comment by zzpin** [comment]
Hey,
I've upgraded Prismatik to 0.30 for Android  but still no option to adjust the brightness is screen capturing mode on the ouya. :(
Please add this option to adjust the brightness.
This will be very helpful.

Thanks.

**Comment by zzpin** [comment]
Hey,

I'm not so happy about the update "Prismatik 0.30"
The performance of my holl device, interface apps (ouya) is lagge and this each time when I enable screen capturing mode. (I've checked other topics here and 0.30 has performance leeks...)
I've unistalled this version and installed again "Prismatik 0.21 beta"
Everything is back normal now, only NO option to adjust the brightness...

Hope for a fix quickly

Rgds,
ZzpiN
