### ISSUE TITLE
Prismatik crashes 

### ISSUE THREAD

**Issue by kotzo** [woodenshark/prismatik-for-android#54]
Hi,

Received Yday my new lightpack.

Android TV (rooted)

Android 4.2.2
processor:ARMv7 Processor rev 0 (v7l)
Armeabi-v7a, armeabi
Kernel: 3.0.36+(eng.dl.20131122.162235)
Compilation: rk31sdk-eng 4.2.2 JDQ39 eng.dl.20131122.162235 test-keys
GPU: Mali-400 MP
Resolution: 1920x1080

Prismatik recognizes the lightpack.
Prismatik does not capture screen.
Prismatik fails the test but works with the rest  of the modes (mood, etc)
Prismatik crashes ramdomly and restarts. Sometimes it reboots the device

I Used Prismatik 0.4 and 0.3 with no luck

Upgraded to 4.4, downgraded again to 4.2.

Every 30 sec, supersu displays the message: "prismatic of lightpack has been granted ......"

What additional information do you need ?

Regards,

K. Tzovanis

**Comment by e-yes** [comment]
Could you pastebin logcat output?

**Comment by kotzo** [comment]
Hi,

Where can I find the log file ?

 -----Ο χρήστης Alexey Roslyakov notifications@github.com έγραψε: -----

 =======================
 Προς: woodenshark/prismatik-for-android prismatik-for-android@noreply.github.com
 Από: Alexey Roslyakov notifications@github.com
 Ημερομηνία: 02/01/2015 07:41ΠΜ 
 Κοιν.: kotzo kotzo@hol.gr
 Θέμα: Re: [prismatik-for-android] Prismatik crashes  (#54)
 =======================
   Could you pastebin logcat output?

---

**Comment by kotzo** [comment]
Hi,

Here is the err log:

http://pastebin.com/xFsqjLuU  

 -----Ο χρήστης Alexey Roslyakov notifications@github.com έγραψε: -----

 =======================
 Προς: woodenshark/prismatik-for-android prismatik-for-android@noreply.github.com
 Από: Alexey Roslyakov notifications@github.com
 Ημερομηνία: 02/01/2015 03:41ΜΜ 
 Κοιν.: kotzo kotzo@hol.gr
 Θέμα: Re: [prismatik-for-android] Prismatik crashes  (#54)
 =======================
   Could you pastebin logcat output?

---

**Comment by e-yes** [comment]
We've fixed this already, wait a little bit for new release.
Duplicate to https://github.com/woodenshark/prismatik-for-android/issues/41
